# 3.1 넘파이 배열

In [1]:
import numpy as np

In [2]:
k1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(k1)
type(k1)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

# 벡터화 연산

In [3]:
# 리스트
data = [0,1,2,3,4,5,6,7,8,9]

# 베열
x = np.array(data)

# 리스트와 달리 배열은 벡터화 연산이 가능
print(data * 2)
print(x * 2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  2  4  6  8 10 12 14 16 18]


# 2차원 배열

In [7]:
# 2 x 3 행렬
m1 = np.array([[0,1,2],
               [3,4,5]])
print(m1)

# 행의 갯수
print(len(m1))

# 열의 갯수
print(len(m1[0]))

[[0 1 2]
 [3 4 5]]
2
3


# 연습문제 1
넘파이를 사용하여 다음과 같은 행렬을 만든다.

```
10 20 30 40
50 60 70 80
```

In [8]:
# 2 x 4 행렬
k2 = np.array( [[10,20,30,40],
                [50,60,70,80]])
print(k2)

[[10 20 30 40]
 [50 60 70 80]]


# 3차원 배열

In [9]:
# 2 x 3 x 4 행렬
k3 = np.array([[[1,2,3,4],
                [5,6,7,8],
                [10,11,12,13]],
               
               [[14,15,16,17],
                [18,19,20,21],
                [22,23,24,25]]])
print(k3)

# 차원, 행, 열의 갯수
print(len(k3))
print(len(k3[0]))
print(len(k3[0][0]))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]]
2
3
4


# 배열의 차원과 크기

In [10]:
# 1차원
a1 = np.array([1,2,3])

# 2차원
a2 = np.array([[0,1,2],
               [3,4,5]])

# 3차원
a3 = np.array([[[1,2,3,4],
                [5,6,7,8],
                [10,11,12,13]],
               
               [[14,15,16,17],
                [18,19,20,21],
                [22,23,24,25]]])

print("차원:", a1.ndim, "크기:", a1.shape)
print("차원:", a2.ndim, "크기:", a2.shape)
print("차원:", a3.ndim, "크기:", a3.shape)

차원: 1 크기: (3,)
차원: 2 크기: (2, 3)
차원: 3 크기: (2, 3, 4)


# 배열의 인덱싱

In [11]:
# 1차원 배열의 인덱싱 (리스트와 같음)
b1 = np.array([0,1,2,3,4])

print(b1[1])
print(b1[-1])

1
4


In [15]:
# 2차원 배열의 인덱싱
b2 = np.array([[0,1,2],
               [3,4,5]])

print(b2[0,0])
print(b2[-1,-1])

0
5


In [16]:
# 3차원 배열의 인덱싱
b3 = np.array([[[1,2,3,4],
                [5,6,7,8],
                [10,11,12,13]],
               
               [[14,15,16,17],
                [18,19,20,21],
                [22,23,24,25]]])

print(b3[1,1,1])
print(b3[1,2,3])

19
25


# 배열 슬라이싱

In [18]:
k = np.array([[0,1,2,3],
              [4,5,6,7]])

# 두번째 행 전체
print(k[1, :])

# 첫번째 열 전체
print(k[:,0])

# 첫번째 행의 두번째 열부터 끝까지
print(k[0,1:])

# k[행 슬라이싱, 열 슬라이싱]
print(k[:2, :2])

[4 5 6 7]
[0 4]
[1 2 3]
[[0 1]
 [4 5]]


# 연습문제 2
다음 행렬과 같은 행렬이 있다.

```
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
```

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [21]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

print(m[1,2])
print(m[-1,-1])
print(m[1,1:3])
print(m[1:,2])
print(m[:2,-2:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


# 배열 인덱싱 (fancy indexing)

In [22]:
# 배열에 다른 배열을 위치정보로 사용
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [23]:
# 위 과정을 단순하게
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [24]:
# 정수 배열을 이용해서 출력
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8]) # 홀수 원소

a[idx]

array([11, 33, 55, 77, 99])

In [25]:
# 위치정보 배열의 크기가 더 큰 경우
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [28]:
# 2차원 배열
k = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 모든 행과 2,3열
print(k[:, [False, True, True, False]])

# 열 순서 바꿔 출력
print(k[:,[3,1,2,0]])

[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 4  2  3  1]
 [ 8  6  7  5]
 [12 10 11  9]]


# 연습문제 3
다음 행렬과 같은 배열이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [36]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 3의 배수
print(x[x % 3 == 0])

# 4의 배수 + 1
print(x[x % 4 == 1])

# 3의 배수 & 4의 배수 + 1
x2 = x[x % 3 == 0]
x3 = x2[x2 % 4 == 1]

print(x3)

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
