# 3.2 배열의 생성과 변형

# 넘파이의 자료형

In [1]:
import numpy as np

In [2]:
# dtype을 이용해 자료형태 확인
x = np.array([0,1,2])

print(x.dtype)

# 배열 생성시 자료형태를 지정하지 않으면 자동으로 유추
x = np.array([0,1,2.0])

print(x.dtype)

int32
float64


# dtype 종류

| dtype 접두사 | 설명 | 사용 예 |
|-|-|-|
| `b` | 불리언 | `b` (참 혹은 거짓) | 
| `i` | 정수 | `i8` (64비트) | 
| `u` | 부호 없는 정수 | `u8` (64비트) | 
| `f` | 부동소수점 | `f8` (64비트) | 
| `c` | 복소 부동소수점 | `c16` (128비트) | 
| `O` | 객체 | `0` (객체에 대한 포인터) | 
| `S` | 바이트 문자열 | `S24` (24 글자) | 
| `U` | 유니코드 문자열 | `U24` (24 유니코드 글자) | 

In [3]:
x = np.array([1,2,3], dtype = 'f')

print(x[0] + x[1])

x = np.array([1,2,3], dtype = 'U')

print(x[0] + x[1])

3.0
12


# Inf와 NaN

In [4]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

<ipython-input-4-6ab12ec6e7a4>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
<ipython-input-4-6ab12ec6e7a4>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [5]:
print(np.log(0))
print(np.exp(-np.inf))

-inf
0.0


<ipython-input-5-0d5d201f1928>:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(0))


# 배열 생성

In [6]:
# 모든 값이 0인 행렬
z1 = np.zeros(5)
z2 = np.zeros((2,2))

print(z1)
print(z2)

# 모든 값이 1인 행렬
o1 = np.ones(5)
o2 = np.ones((2,2))

print(o1)
print(o2)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [7]:
# 자료형 지정 가능
z = np.zeros((5, 2), dtype="i")
z

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [8]:
# 문자로 지정시 크기에 유의
z = np.zeros(5, dtype="U4")

z[0] = "a"
z[1] = "abcd"
z[2] = "abcde" # 짤려서 나옴

print(z)

['a' 'abcd' 'abcd' '' '']


In [9]:
# 다른 배열과 같은 크기로 생성하기
z = np.zeros(5)
o = np.ones_like(z, dtype= "f")
o

array([1., 1., 1., 1., 1.], dtype=float32)

In [10]:
# empty: 배열을 생성만 하고 값은 초기화 하지 않음 (가장 빠른 속도)
e = np.empty((2, 2))
e

array([[1., 1.],
       [1., 1.]])

In [11]:
# np.arange: 리스트의 range 역할
print(np.arange(5))

# np.arange(시작, 끝, 단계)
print(np.arange(1,11,2))

[0 1 2 3 4]
[1 3 5 7 9]


In [12]:
# linsapce(시작, 끝(포함), 나눌 수)
print(np.linspace(1,10,4))

# logspace(시작, 끝(포함), 나눌 수)
print(np.logspace(0.1,1,4)) # 10**0.1 ~ 10

[ 1.  4.  7. 10.]
[ 1.25892541  2.51188643  5.01187234 10.        ]


# 전치 연산

In [13]:
M = np.array([[0,1,2],
              [3,4,5]])
print(M) # 2 x 3
print(M.T) # 3 x 2

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


# 배열의 크기 변형

In [14]:
x = np.arange(12)

# 2차원으로 변환
x2 = x.reshape(3,4)
print(x2)

# 3차원으로 변환
x3 = x.reshape(2,2,3)
print(x3)

# -1을 이용하여 자동으로 지정
x4 = x.reshape(2,-1)
print(x4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [15]:
# 무조건 1차원으로 배열 만들기 - flatten, ravel
x = np.arange(12)
x2 = x.reshape(4,3)
x3 = x2.flatten()
x4 = x2.ravel()

print(x)
print(x2)
print(x3)
print(x4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
# 차원 확인하기
# 같은 데이터여도 1차원과 2차원은 확실히 다른 객체
x = np.arange(3)
x2 = x.reshape(1,3)

print(x, "차원:", x.ndim)
print(x2, "차원:", x2.ndim)

[0 1 2] 차원: 1
[[0 1 2]] 차원: 2


In [17]:
# 1차원 증가시키기 - newaxis
x = np.arange(3)
print(x[:, np.newaxis])
print(x[np.newaxis, :])

[[0]
 [1]
 [2]]
[[0 1 2]]


# 배열 연결

In [18]:
# hstack: 행의 수가 같아야함
x = np.zeros((2,3))
y = np.ones((2,5))

np.hstack([x,y])

array([[0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1.]])

In [19]:
# vstack: 열의 수가 같아야함
x = np.zeros((2,4))
y = np.ones((1,4))

np.vstack([x,y])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [20]:
# dstack: 행과 열의 수가 같아야함
x = np.zeros((4,3))
y = np.ones((4,3))

# 기존 4 x 3 -> 4 x 3 x 2
# dstack으로 마지막 x 2가 추가되어 행과 열의 수도 바뀜
np.dstack([x,y])

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [21]:
# stack: 행과 열의 수가 같아야함 - dstack의 확장버전
x = np.arange(12) ; x = x.reshape((4,3))
y = np.arange(12) ; y = y.reshape((4,3))

# 기존 4 x 3 -> 2 x 4 x 3 - 깊이 연결
print(np.stack([x,y]))
print("-" * 20)

# 기존 4 x 3 -> 4 x 2 x 3  - 행 연결
print(np.stack([x,y], axis = 1))
print("-" * 20)

# 기존 4 x 3 -> 4 x 3 x 2 - 행 연결 후 전치
print(np.stack([x,y], axis = 2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]
--------------------
[[[ 0  1  2]
  [ 0  1  2]]

 [[ 3  4  5]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 6  7  8]]

 [[ 9 10 11]
  [ 9 10 11]]]
--------------------
[[[ 0  0]
  [ 1  1]
  [ 2  2]]

 [[ 3  3]
  [ 4  4]
  [ 5  5]]

 [[ 6  6]
  [ 7  7]
  [ 8  8]]

 [[ 9  9]
  [10 10]
  [11 11]]]


In [22]:
# r_: hstack과 비슷
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [23]:
# c_: 차원을 증가시킨 후 연결
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
# tile: 동일한 배열을 반복하여 연결
a = np.array([[0, 1, 2],
              [3, 4, 5]])

print(np.tile(a, 3)) # 1개 지정시 hstack
print(np.tile(a, (3,2)))

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


# 연습문제 3.2.1
지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.

```
array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])
```

In [25]:
z1 = np.zeros((3,3))
o1 = np.ones((3,2))

m1 = np.arange(10, 151, 10)
m2 = m1.reshape((3,5))

k1 = np.hstack([z1,o1])
k2 = np.vstack([k1,m2])

k3 = np.tile(k2,(2,1))
k3

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

# 2차원 그리드 포인트 생성

In [26]:
# 좌표 만들기
x = np.arange(3)
y = np.arange(5)

# np.meshgrid
# X: 5 x 3 - vstack / Y: 5 x 3 - hstack
X, Y = np.meshgrid(x,y)
print(X)
print("-" * 20)

print(Y)
print("-" * 20)

# zip: pair를 만들어줌
[list(zip(x, y)) for x, y in zip(X, Y)]

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
--------------------
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
--------------------


[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]