# 3.3 배열의 연산

In [1]:
import numpy as np

# 벡터화 연산

In [2]:
# 리스트
x = list(range(1,11))
y = list(range(11,21))

z = x + y
print(z)

# 배열
x = np.arange(1, 11)
y = np.arange(11, 21)

z = x + y
print(z)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[12 14 16 18 20 22 24 26 28 30]


In [3]:
# 논리연산
x = np.array([1,2,3,4])
y = np.array([3,2,1,4])

print(x == y)
print(x >= y)

[False  True False  True]
[False  True  True  True]


In [4]:
# 모든 배열의 원소 검증
x = np.array([1,2,3,4])
y = np.array([3,2,1,4])
z = np.array([1,2,3,4])

print(np.all(x == y))
print(np.all(x == z))

False
True


In [5]:
# 지수함수, 로그함수 적용
x = np.array([1,2,3,4])

print(np.exp(x))
print(np.log(x))
print(x ** 2)

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 1  4  9 16]


# 스칼라와 벡터/행렬의 곱셈

In [6]:
# 스칼라 곱셈
x = np.arange(12).reshape(3,4)

100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [7]:
# 행렬 곱셈
x = np.arange(4).reshape(2,2) # 2 x 2
y = np.arange(2).reshape(1,2) # 1 x 2

print(x)
print("-" * 10)
print(y)
print("-" * 10)
print(y * x)

[[0 1]
 [2 3]]
----------
[[0 1]]
----------
[[0 1]
 [0 3]]


# 브로드캐스팅

In [8]:
# 브로드캐스팅: 행렬 연산시 크기가 작은 배열을 자동으로 확장시켜주는 기능
x = np.arange(5)
y = np.ones_like(x)

# 크기가 같은 행렬 덧셈
print(x + y)

# 행렬 + 1
print(x + 1)

[1 2 3 4 5]
[1 2 3 4 5]


In [9]:
# 다차원에서도 적용가능
# 5 x 3 행렬
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
print(x)
print("-" * 10)

# 5 x 1 행렬
y = np.arange(5)[:,np.newaxis]
print(y)
print("-" * 10)

# 자동으로 y 행렬을 확장해서 연산
print(x + y)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
----------
[[0]
 [1]
 [2]
 [3]
 [4]]
----------
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


# 차원 축소 연산

In [10]:
# 행별로 연산
x = np.array([1, 2, 3, 5])

# 합계
print("합계:", np.sum(x))
print("합계:", x.sum())

# 최소값, 최대값
print("최소값:", x.min())
print("최대값:", x.max())

# 최소값, 최대값 위치
print("최소값 위치:", x.argmin())
print("최대값 위치:", x.argmax())

# 평균
print("평균:", x.mean())

# 중앙값
print("중앙값:", np.median(x))

합계: 11
합계: 11
최소값: 1
최대값: 5
최소값 위치: 0
최대값 위치: 3
평균: 2.75
중앙값: 2.5


In [11]:
# 논리 연산 - all, any
a = np.zeros((4, 4), dtype=np.int)

print(a)
print(np.any(a != 0))
print(np.all(a == a))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
False
True


In [12]:
# 2차원 배열 축소 연산
x = np.arange(4).reshape(2,2)
print(x)

# 전체 원소 합계
print("전체 합계:", x.sum())

# 열 합계
print("열 합계:", x.sum(axis=0))

# 행 합계
print("행 합계:", x.sum(axis=1))

[[0 1]
 [2 3]]
전체 합계: 6
열 합계: [2 4]
행 합계: [1 5]


# 연습문제 3.3.1
실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

1. 전체의 최댓값
1. 각 행의 합
1. 각 행의 최댓값
1. 각 열의 평균
1. 각 열의 최솟값

In [13]:
x = np.arange(30).reshape(5,6)

print(x)
print("1. 전체의 최댓값:", x.max())
print("2. 각 행의 합:", x.sum(1))
print("3. 각 행의 최댓값:", x.max(axis=1))
print("4. 각 열의 평균:", x.mean(0))
print("5. 각 열의 최솟값:", x.min(axis=0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
1. 전체의 최댓값: 29
2. 각 행의 합: [ 15  51  87 123 159]
3. 각 행의 최댓값: [ 5 11 17 23 29]
4. 각 열의 평균: [12. 13. 14. 15. 16. 17.]
5. 각 열의 최솟값: [0 1 2 3 4 5]


# 정렬

In [14]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])

# 디폴트 값은 axis = -1로 a x b x c이면 a기준 정렬
print(np.sort(a))
print("-" * 20)

# 행 정렬
print(np.sort(a, axis=1))
print("-" * 20)

# 열 정렬
print(np.sort(a, axis=0))
print("-" * 20)

# .sort로 정렬 시 배열이 변경된 채로 저장
a.sort(axis=1)
print(a)

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
--------------------
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
--------------------
[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 11 14]]
--------------------
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]


In [15]:
# 정렬시 순서만 알고 싶은 경우
a = np.array([42, 38, 12, 25])
j = np.argsort(a)

print(j) # 기존 배열에서 정렬된 형태로 나오게 하기 위한 순서
print(a[j])

[2 3 1 0]
[12 25 38 42]


# 연습문제 3.3.2
다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

```
array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
```

In [16]:
x = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71],
              [ 81,   59,   90,  100]])

# 단순 열 정렬 하였음
np.sort(x, axis=0)

array([[  1,   2,   3,   4],
       [ 46,  59,  90,  71],
       [ 81,  99, 100, 100]])