# 3.5 난수 발생과 카운팅

In [1]:
import numpy as np

In [2]:
# 시드 설정하기 (시드를 설정하면 같은 난수가 발생)
np.random.seed(0)

# 난수 발생
np.random.rand(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [3]:
# suffle - 데이터의 순서 바꾸기
x = np.arange(10)

np.random.shuffle(x)
x

array([8, 6, 4, 0, 2, 5, 9, 1, 7, 3])

# 데이터 샘플링

In [4]:
# numpy.random.choice(a, size = None, replace = True, p = None)
# a: 배열 입력, 정수 입력시 arrange(a)로 인식
# size: 추출할 샘플 갯수
# replace: 복원 추출 여부
# p: 배열의 각 데이터가 추출 될 확률

In [5]:
# shuffle과 같음
np.random.choice(5,5,replace=False)

array([3, 1, 2, 4, 0])

In [6]:
# 일부 추출
np.random.choice(5,2,replace=False)

array([4, 2])

In [7]:
# 복원 추출
np.random.choice(5,7)

array([0, 1, 4, 3, 0, 3, 0])

In [8]:
# 확률을 부여해서 복원 추출
np.random.choice(5,10, p = [0.1, 0, 0.4, 0.5, 0])

array([3, 3, 2, 3, 2, 3, 2, 3, 3, 2])

# 난수 생성

In [9]:
# rand: 0~1 사이 uniform
# randn: standard normal
# ranint: 0~정수 사이 uniform

In [10]:
# 균일 분포
print(np.random.rand(5))
print(np.random.rand(2,2))

[0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
[[0.6176355  0.61209572]
 [0.616934   0.94374808]]


In [11]:
# 표준 정규 분포
print(np.random.randn(5))
print(np.random.randn(2,2))

[-1.078278    1.39547227  1.78748405 -0.56951726  0.17538653]
[[-0.46250554 -1.0858006 ]
 [ 0.63973599 -0.38586334]]


In [12]:
# 균일 분포2
print(np.random.randint(10, size=5)) # 0 ~ 10 사이
print(np.random.randint(10, 20, size=5)) # 10 ~ 20 사이
print(np.random.randint(10, 20, size=(2, 2))) # 10 ~ 20 사이 행렬

[5 9 4 4 6]
[14 14 13 14 14]
[[18 14]
 [13 17]]


# 연습 문제 3.5.1
```

1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
```

In [13]:
# 1. 동전 실험
print(np.random.randint(0, 2, size=10))

# 2. 주사위 평균
dice = np.random.randint(1,7, size = 100)
print(np.mean(dice))

[1 1 1 1 0 1 1 1 1 0]
3.32


# 연습 문제 3.5.2

```

가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.
250일 동안의 주가를 무작위로 생성하라
```

In [14]:
price = np.ones(250) * 10000
x = np.random.randn(250)

# 전일 종가대비로 작성하지 않고 다음과 같은 수식으로 계산
# 10,000원 + (10,000원 x 수익률)
price + (price * x / 100)

array([ 9922.42376466,  9872.95150015, 10096.93967082,  9882.68765949,
       10194.36211856,  9958.63810192,  9925.25451886, 10192.29420265,
       10148.05147914, 10186.75589604, 10090.60446583,  9913.87743149,
       10191.00649531,  9973.1996629 , 10080.24563958, 10094.72519678,
        9984.49899069, 10061.40793703, 10092.22066716, 10037.64255312,
        9890.05992094, 10029.82381742, 10132.63858967,  9930.54321403,
        9985.03654597,  9956.48464483, 10184.92637285, 10067.2294757 ,
       10040.74618362,  9923.00839256, 10053.92491913,  9932.56673393,
       10003.18305583,  9936.41539216, 10067.64332949, 10057.65908166,
        9979.17012444, 10039.60067127,  9890.69384913,  9850.87424073,
       10043.93917013, 10016.66734954, 10063.50314369, 10238.31447749,
       10094.4479487 ,  9908.71777746, 10111.70162881,  9868.40925895,
        9953.84153952,  9993.17583947, 10171.33427216,  9925.5245178 ,
        9917.35614613,  9990.15474756,  9933.65217136, 10112.66359221,
      

# 정수 데이터 카운팅

In [15]:
# 정수 데이터 카운팅
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [16]:
# 데이터와 그에 따른 개수
x = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(x, return_counts=True)

print(index, count)

['a' 'b' 'c'] [2 2 1]


In [17]:
# 주사위 나온 눈의 개수
# bincount에서 minlength 지정시 0 ~ minlength -1 만큼의 요소별 개수가 출력
# 실제로 데이터가 없어도 개수 0으로 출력
dice = np.random.randint(1,7, size = 5)
print(dice)
print(np.bincount(dice, minlength=10))

[2 1 5 2 3]
[0 1 2 1 0 1 0 0 0 0]
